// 指定“构建插件”从哪些官方仓库查找。
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

// 统一管理普通依赖仓库，禁止子模块私自添加来源，降低供应链风险。
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

// 构建工程名称，仅影响开发工具中的工程显示名称。
rootProject.name = "ChaChaCalendar"
// 本工程只有一个安卓应用模块。
include ':app'
